version: '3.4'

networks:
    dev:
        driver: bridge

services:

    mail:
        image: maildev/maildev
        restart: always
        container_name: mail
        networks:
            - dev
        ports: 
            - "1080:1080"
            - "1025:1025"
    db:
        image: postgres:alpine
        restart: always
        container_name: db
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gamesync
          POSTGRES_ENCODING: UTF-8
        volumes:
           - ./data:/var/lib/postgresql/data
        networks:
            - dev
        ports:
            - "5432:5432"
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 1s
          timeout: 20s
          retries: 60
    app:
        depends_on:
          db:
            condition: service_healthy
        container_name: app
        image: gamesync.azurecr.io/gamesyncapi:latest
        build: 
            context: .
            args:
                - "CMD=docker"
        environment:
            - "ConnectionStrings__Default=User ID=postgres;Password=postgres;Host=db;Port=5432;Database=gamesync;"
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "Smtp__Host=mail"
            - "Smtp__Port=1025"
            - "Smtp__From=no-reply@gamesync.com"
        networks:
            - dev
        ports:
           - "1092:80"