version: '3.4'

networks:
    dev:
        driver: bridge

services:
    db:
        image: postgres:alpine
        restart: always
        container_name: db
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gamesync
          POSTGRES_ENCODING: UTF-8
        volumes:
           - ./data:/var/lib/postgresql/data
        networks:
            - dev
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 1s
          timeout: 20s
          retries: 60
    app:
        depends_on:
          db:
            condition: service_healthy
        container_name: app
        image: gamesync.azurecr.io/gamesyncapi:latest
        build: .
        environment:
            - "ConnectionStrings__Default=User ID=postgres;Password=postgres;Host=db;Port=5432;Database=gamesync;"
        networks:
            - dev
        ports:
           - "80:80"