//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.864.0 using the following command:
// XmlSchemaClassGenerator.Console .\v2\thing.xsd
using System.Collections.ObjectModel;
using System.Xml.Serialization;

namespace GameSync.Business.BoardGamesGeek.Schemas.Thing
{


    [Serializable]
    public class ThingItem
    {
        [XmlElement("image")]
        public string Image { get; set; }
        
        [XmlElement("thumbnail")]
        public string Thumbnail { get; set; }
    }

    [Serializable]
    [XmlRoot(ElementName = "items")]
    public class ThingRoot
    {

        [XmlElement(ElementName = "item")]
        public Collection<ThingItem> Items { get; set; } 

    }
    
}
