# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: cicd
env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  PUB_PATH: ./GameSync.Api/publish
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  
jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Test
      run: dotnet test GameSync.sln --configuration Release
      
    - name: Logging into the ACR registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: GameSync.azurecr.io/gamesyncapi:latest